### PR TITLE
Reduce shell.nix to minimal working implementation

### PR DESCRIPTION
**Pull request by turion**
Makes #29 superfluous

### CODE REVIEW

**Comment by coot** [comment]
I prefer to not expose `shell.nix`.  I just want to as little `nix` as possible to maintain. `cabal` nix-style builds are good enough for dev work.

**Comment by turion** [comment]
How do you work then? How do you build the project? I can't get a feasible working environment currently. On `master`, `nix-shell` recompiles `ghc`, even after doing `niv update`.

**Comment by coot** [comment]
I simply run `cabal build free-category`, I use `ghc-8.10.2` now, I used to use `ghc-8.6.5` before without any problems.

```
cabal --version
cabal-install version 3.4.0.0
```
More precisely it's `3.4.0.0-rc4` but `3.2` should work too, and likely anything above `3.0` should work too.

**Comment by turion** [comment]
Ok, so you don't use `nix` to install hackage dependencies?

**Comment by coot** [comment]
> Ok, so you don't use nix to install hackage dependencies?

Right, I don't.  Since version `3.0` `cabal-intsall` is using nix style local builds.  One can even simulate nix with a mix of a freeze file and `index-state` in `cabal.project` file (obviously `cabal` cannot deal with external dependencies, but we don't have any here).

**Pull request closed without merging**
